version: '3'

volumes:
  composer:

services:

  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
      - composer:/home/noroot/.composer
    tty: true
    stdin_open: true
