#!/usr/bin/env php
<?php

declare(strict_types=1);

$possibleFiles = [
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/../autoload.php',
    __DIR__ . '/../../../autoload.php',
    __DIR__ . '/vendor/autoload.php',
    __DIR__ . '/../vendor/autoload.php',
];

$file = null;

foreach ($possibleFiles as $possibleFile) {
    if (file_exists($possibleFile)) {
        $file = $possibleFile;

        break;
    }
}

if ($file === null) {
    throw new RuntimeException('Unable to locate autoload.php file.');
}

require_once $file;

use Esst\TranslationExtractor\Commands\ExtractCommand;
use Symfony\Component\Console\Application;

$dotEnv = Dotenv\Dotenv::createUnsafeImmutable(
    dirname(__DIR__),
    ['.env', '.env.dist']
);
$dotEnv->load();

$application = new Application();
$application->add(new ExtractCommand());
$application->run();

